import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const morraba = localFont({
  src: [
    { path: "./fonts/regular.woff2", style: "normal" },
    { path: "./fonts/dana.woff2", style: "bold" },
  ],
  display: "swap",
  variable: "--font-morabba",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${morraba.variable} font-morabba`}>{children}</body>
    </html>
  );
}
