import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import HolyLoader from "holy-loader";
import { Toaster } from "sonner";
import Header from "@/templates/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const morraba = localFont({
  src: [
    { path: "./fonts/hilda.ttf", style: "bold" },
    { path: "./fonts/dana.ttf", style: "normal" },
  ],
  display: "swap",
  variable: "--font-morabba",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${morraba.variable} font-morabba px-4`}>
        <Header />
        {children}
        <p>
          لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با
          استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در
          ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و
          کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی
          در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می
          طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی
          الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این
          صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و
          شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای
          اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده
          قرار گیرد. 165156
        </p>
        <HolyLoader
          color="linear-gradient(to right, red, orange)"
          height="3px"
          speed={250}
          easing="linear"
          showSpinner
          dir="rtl"
        />
        <Toaster
          richColors
          closeButton
          toastOptions={{ className: "font-morabba" }}
        />
      </body>
    </html>
  );
}
