import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import HolyLoader from "holy-loader";
import { Toaster } from "sonner";
import Header from "@/templates/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const morraba = localFont({
  src: [
    { path: "./fonts/regular.woff2", style: "normal" },
    { path: "./fonts/dana.woff2", style: "bold" },
  ],
  display: "swap",
  variable: "--font-morabba",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${morraba.variable} font-morabba px-4`}>
        <Header />
        {children}
        <HolyLoader
          color="linear-gradient(to right, red, orange)"
          height="3px"
          speed={250}
          easing="linear"
          showSpinner
          dir="rtl"
        />
        <Toaster
          richColors
          closeButton
          toastOptions={{ className: "font-morabba" }}
        />
      </body>
    </html>
  );
}
